#coding: utf_8


s1 = 'TACTTTAAGCGAAATGCATGCAAGGTATCCTCAGGCACTATCGGCTCAAGCGCCCCGCTTGAATGCGCCCTACCATTAGGCCGACACAAATGGACGGTTCTCTTTCAGTTTGTTCACCTACGTAGTACGGGGCCGAATCAGCAGTGCCGTCTTACGGTATTTACGACCCGTACAACCGCGTAAAATTTTCATTAAGCGCCAACGCAGTATTCCAGTGACGTTTCGCATCCGTCGTGTCCTCCTGGAGGGAATCCATGCTTTTTTTTCTCCGGGATGTATCAGTCAGTACGGGGAGCCGAGTTACCGGATACGGCAACTCGCGTTAGCCATTCTTTCTCTGAAGTAAGGATTACCGGCGGTTGACGGCGATTGTTGCAGCAGTAACAGCGCGGAGCATGCAAGCCGATGCCTACGGGCTTCGGCTACCGGGTGTGTTAAATTTTGCCCAAAAAAAGCATTGGCCCTGATACCGATACGACTGAAGGCGAGTTGGTACACTTATGCTTATAGGTGGGTATATTCTCCATGGTGTCCATATGTAACCGACCCTTCTTTCTATAACCGCGACGTGGGGGAACCATCCTTCTGCTGGATAGTTATGGTTCAAGCTAAGGGGAACGGGAGGAGGGCTGATGCCGCTCCGGCGTGTGTCTAGTGCTTAATAGCGATGCATAATTAAGATGCGTGGCCACGGGAAGTACTTTTAACGACTACTAGAGTTATCTTAGCGGAAAGGGCAGACTCTGTAAAGATGGTGTATTCACCTAAATGCAGCCGACCATTAGAGGGCCTTATGTGCATCGCACTAGGTGAGACAATTCTCGAGTAGGGAGACTATAAGGGCATGGTAAGGAGCGGGATACGACATGAAATTCAAACCAACCGCATAATCG'
s2 = 'TACTTTAAGTGGAATGCGTGCAATATGTCCTCGGGCCCTATTGGCCCAAACGCCCCGTCTCAGGACGCCCCACCATCACACGGACACAAGGATCCGTTTCCCATCCAGTTTATTTACCTACGTAACAAAAAACCAAACCAGCAATGCTGGTCTACCACCATCAAAAGCTGTATAACCACGCGCGATCTTCGTTGAGCATCAACGTAACAACCCAGTGACGTTTCGAAGCCTTCGTATACTTCTGGAGGAAATCCATGCTTCACCCTGCCCGGTATGCGGCTGTCAGTACGGGTACCCGAGTTACTGGATCTGGCAACCGGCGTCAGCCATTGTTTCCGTGGAGTGCGATTTGGCGGCGGTTGACGGTCACTGCCATAAGAACCACAGTACGGAACACACAAGCCTGTACCTAAATACATCGATCACCGGGTGTGCTGAATACTGCCCAAAAAAAGGATCGGTCTCGATACTGATATAACCTGACGCCACCTCATGCATTTATGCTCAAGAGTGGGGATACTCCCGATGTTGTCCGTGCTCAACCGACCTTTCCCTCTATAACGGCAAGAGCGGGAAGCCAGCCTTCTGCCGGATAATTGTGGTTCAAATGAACAGGAACATGAGAAGGGCTTGTGCCACTTAGGCGTGTGTCCCGTGCCTAATAGTGTAACATGATCAGAATTCAGGACCACGGAGAGCACCGTTAGTGCCCACTAGAGCTACCTCAGTGGAAGCGGTCGACTCTGCGGAGACGGGATATTCGCCTAAATACCGTTGACCTTTAGAGGGCCTCTAATAAATGGCGTTAGGCGTGACAATTCCCGAGTTGGCAGATGATAAGAGTATGAGATGGATCAGAGTATAACCTGAAGGCCGTAGCGACCTCATGATCG'
a = 0; b = 0; c = 0;
for i in range(len(s1)):

    if s1[i]==s2[i]: a = a + 1;
    elif s1[i] == 'A' and  s2[i] == 'G': b = b+1;
    elif s1[i] == 'G' and  s2[i] == 'A': b = b+1;
    elif s1[i] == 'C' and  s2[i] == 'T': b = b+1;
    elif s1[i] == 'T' and  s2[i] == 'C': b = b+1;
    else: c = c+1;

print float(b)/c

        

